### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by NezaLesnjak** [NezaLesnjak/APPR-2020-21#2]
Pozdravljeni, mislim da sem z delom na projektu končala. Je potrebno še kaj spremeniti ali dodati?

**Comment by timotejvesel** [comment]
Predlagam, da pri prvih dveh grafih v poročilu oznake na x osi obrneš za 90 stopinj: 
```r
graf_izobrazba.moski <- ggplot(filter(tabela_po_izobrazbi, spol == 'Moški'), 
                          aes(x=leto, y=stevilo, col=izobrazba)) + geom_point(size=3) + 
  ggtitle("Delovno aktivni moški glede na izobrazbo") + ylab("Število v 1000") + theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
in podobno za drugi graf.
Sicer pa se mi zdi vredu.

**Comment by jaanos** [comment]
Poleg tega, kar je izpostavil @timotejvesel, nimam drugih pripomb, tako da bom dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora. Če boš do takrat še kaj spreminjala, mi javi, da posodobim povezavo.

**Comment by NezaLesnjak** [comment]
Hvala za pripombo, sem uredila - tako da bi prosila za posodobitev povezave.

**Comment by jaanos** [comment]
V redu, sem posodobil.
